{ inputs, ... }:
{
  perSystem =
    {
      config,
      inputs',
      pkgs,
      ...
    }:
    {
      # Add treefmt binary and any enabled programs to default shell
      make-shells.default.inputsFrom = [ config.treefmt.build.devShell ];
      treefmt = {
        programs.nixfmt = {
          enable = true;
          strict = true;
        };
        # Ignore files generated by yarn-plugin-nixify
        settings.formatter.nixfmt.excludes = [ "*yarn-project.nix" ];
        # Add a check for renovate config files
        settings.formatter.renovate-config-validator = {
          command = "${pkgs.renovate}/bin/renovate-config-validator";
          options = [ "--strict" ];
          includes = [
            "renovate.json"
            "renovate.json5"
          ];

        };
      };
    };
}
